Description: Buy registry certificates online

Parameters:
  ClusterStack:
    Type: String
    Description: Our main stack. Expected to have Cluster, ConfigBucket, Namespace, and ServiceRoleArn outputs
    Default: DigitalAppsCluster

  LoadBalancerStack:
    Type: String
    Description: Stack with the ALB. Expected to have HttpListenerArn, VpcId, LoadBalancerFullName outputs.

  ShortName:
    Type: String
    Default: registry-certs

  PublicDnsName:
    Type: String
    Description: Host name we'll receive traffic from

  CloudFormationTemplatesBucket:
    Type: String
    Description: Bucket for our CloudFormationTemplates so that we can reference them from substacks

  ServiceDesiredCount:
    Type: Number
    Description: Update this and redeploy to change the number of instances of the service
    Default: 0

  LoadBalancerListenerPriority:
    Type: Number
    Description: Priority order in the listener to register our rule

  ContainerPort:
    Type: Number
    Description: Port that the service container listens to traffic on. Must match Dockerfile's expose and .env's $PORT
    Default: 3000

Resources:
  CommonResources:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        ClusterStack: !Ref ClusterStack
        AppStack: !Ref AWS::StackName
        ShortName: !Ref ShortName
        ServiceDesiredCount: !Ref ServiceDesiredCount
      TemplateURL: !Sub 'https://${CloudFormationTemplatesBucket}.s3.amazonaws.com/service/common-resources.yml'

  WebappResources:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        ClusterStack: !Ref ClusterStack
        LoadBalancerStack: !Ref LoadBalancerStack
        AppStack: !Ref AWS::StackName
        ShortName: !Ref ShortName
        PublicDnsName: !Ref PublicDnsName
        LoadBalancerListenerPriority: !Ref LoadBalancerListenerPriority
        LoadBalancerHealthCheckPath: /admin/ok
        ServiceDesiredCount: !Ref ServiceDesiredCount
        ContainerPort: 3000
      TemplateURL: !Sub 'https://${CloudFormationTemplatesBucket}.s3.amazonaws.com/service/webapp-resources.yml'

  Dashboard:
    Type: "AWS::CloudWatch::Dashboard"
    Properties:
      DashboardName: !Ref AWS::StackName
      DashboardBody:
        Fn::Sub:
          - |
            {
              "widgets": [
                {
                  "type": "text",
                  "x": 0,
                  "y": 0,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "markdown": "${Markdown}"
                  }
                },
                {
                  "type": "metric",
                  "x": 12,
                  "y": 0,
                  "width": 12,
                  "height": 6,
                  "properties": ${InstancesDashboardMetricJson}
                },
                {
                  "type": "metric",
                  "x": 0,
                  "y": 6,
                  "width": 12,
                  "height": 3,
                  "properties": ${CpuDashboardMetricJson}
                },
                {
                  "type": "metric",
                  "x": 12,
                  "y": 6,
                  "width": 12,
                  "height": 3,
                  "properties": ${MemoryDashboardMetricJson}
                }
              ]
            }
          - Markdown:
              Fn::Join:
                - '\n'
                - Fn::Split:
                  - "\n"
                  - Fn::Sub:
                    - |
                      # Registry Certs
                      Webapp for ordering certificates from the registry

                      &nbsp;

                      ${ServiceLinks}

                    - ServiceLinks: !GetAtt CommonResources.Outputs.ServiceLinksMarkdown
            InstancesDashboardMetricJson: !GetAtt CommonResources.Outputs.InstancesDashboardMetricJson
            CpuDashboardMetricJson: !GetAtt CommonResources.Outputs.CpuDashboardMetricJson
            MemoryDashboardMetricJson: !GetAtt CommonResources.Outputs.MemoryDashboardMetricJson

  ###### CUSTOM RESOURCES TO THIS APP ######
